# -*- coding: utf-8 -*-
"""reducer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xADlrytgR2SBisbNSEuojfwaP98x1kqP
"""

from operator import itemgetter
import sys

current_word = None
current_count = 0
word = None

#tracking individual tokens
for line in sys.stdin:
    # removing whitespaces from documents
    line = line.strip()
    #converting all tokens to lower case
    line=line.lower()

    # shuffle and sorting of tokens
    word, count = line.split('\t', 1)
    try:
      count = int(count)
    except ValueError:
      #error handling of count not being a number
      continue

    #for word, count pairs if a words has already been seen add one to the count
    #for word, count pairs if a words has not yet been seen add one
    if current_word == word:
        current_count += count
    else:
        if current_word:
            print ('%s\t%s' % (current_word, current_count))
        #final value is total count
        #  final key is word  
        current_count = count
        current_word = word

# printing out the final word, count value pairs
if current_word == word:
    print( '%s\t%s' % (current_word, current_count))